fix: publish artefacts

diff --git a/.github/workflows/publish.yaml b/.github/workflows/publish.yaml
--- a/.github/workflows/publish.yaml
+++ b/.github/workflows/publish.yaml
@@ -57,13 +57,13 @@ jobs:
           echo "SKIP=true" >> $GITHUB_ENV
           exit 0
 
-      - name: Set up QEMU
-        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3
+      # - name: Set up QEMU
+      #   uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3
 
-      - name: Set up Docker Context for Buildx
-        id: buildx-context
-        run: |
-          docker context create builders
+      # - name: Set up Docker Context for Buildx
+      #   id: buildx-context
+      #   run: |
+      #     docker context create builders
 
       - name: Login to GitHub Container Registry
         uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3
@@ -72,25 +72,60 @@ jobs:
           username: ${{ github.actor }}
           password: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Set up Docker Buildx
-        timeout-minutes: 5
-        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3
-        with:
-          version: latest
+      # - name: Set up Docker Buildx
+      #   timeout-minutes: 5
+      #   uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3
+      #   with:
+      #     version: latest
 
       - name: Set up Go
         uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6
         with:
           go-version-file: go.mod
 
-#      - name: Build and Push Images
-#        run: |
-#          task build:img:all --verbose
-#
-#      - name: Package and Push Helm Charts
-#        run: |
-#          task build:helm:all --verbose
+      - name: Cross Build
+        run: |
+          WORK_DIR=$(mktemp -d)
+          echo "WORK_DIR=$WORK_DIR" >> $GITHUB_ENV
+          cd "${WORK_DIR}"
+          mkdir -p dist
 
+          build_matrix=("linux,amd64" "linux,arm64" "darwin,amd64" "darwin,arm64", "windows,amd64")
+
+          for i in "${build_matrix[@]}"; do
+            IFS=',' read os arch <<< "${i}"
+
+            echo "Build $os/$arch"
+            bin_path="dist/landscapercli-$os-$arch"
+
+            CGO_ENABLED=0 GOOS=$os GOARCH=$arch GO111MODULE=on \
+            go build -o $bin_path \
+            -ldflags "-s -w \
+                      -X github.com/openmcp-project/landscapercli/pkg/version.LandscaperCliVersion=${{ env.version }} \
+                      -X github.com/openmcp-project/landscapercli/pkg/version.gitTreeState=$([ -z git status --porcelain 2>/dev/null ] && echo clean || echo dirty) \
+                      -X github.com/openmcp-project/landscapercli/pkg/version.gitCommit=$(git rev-parse --verify HEAD)" \
+            ${WORK_DIR}/landscaper-cli
+
+            # create zipped file
+            gzip -f -k "$bin_path"
+          done
+
+      - name: Upload a Build Artifact
+        uses: actions/upload-artifact@v5.0.0
+        with:
+          # Artifact name
+          # name: # optional, default is artifact
+          # A file, directory or wildcard pattern that describes what to upload
+          path: ${{ env.WORK_DIR }}/dist/*.gz
+          # The desired behavior if no files are found using the provided path.
+          if-no-files-found: error # optional, default is warn
+          # The level of compression for Zlib to be applied to the artifact archive. The value can range from 0 to 9: - 0: No compression - 1: Best speed - 6: Default compression (same as GNU Gzip) - 9: Best compression Higher levels will result in better compression, but will take longer to complete. For large files that are not easily compressed, a value of 0 is recommended for significantly faster uploads.
+          compression-level: 0 # optional, default is 6
+          # If true, an artifact with a matching name will be deleted before a new one is uploaded. If false, the action will fail if an artifact for the given name already exists. Does not fail if the artifact does not exist.
+          overwrite: false # optional, default is false
+          # If true, hidden files will be included in the artifact. If false, hidden files will be excluded from the artifact.
+          include-hidden-files: false # optional, default is false
+          
       - name: Build and Push OCM Component
         run: |
           task build:ocm:all --verbose
